---

- name: Create RabbitMQ NFS Path
  ansible.builtin.file:
    state: directory
    path: /nfs/rabbitmq

- name: Get Storage IP
  ansible.builtin.include_role:
    name: storage
    tasks_from: get_ip

- name: Create Queue Namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: queue

- name: Create RabbitMQ PersistentVolume
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: rabbitmq-nfs-pv
        labels:
          directory: rabbitmq
      spec:
        capacity:
          storage: 10Gi
        accessModes:
          - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: slow
        volumeMode: Filesystem
        nfs:
          path: /rabbitmq
          server: "{{ storage_ip }}"

- name: Create RabbitMQ PersistentVolumeClaim
  register: pvc
  until: pvc.result.status.phase | d(None) == "Bound"
  retries: 5
  delay: 10
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: rabbitmq-nfs-pvc
        namespace: queue
      spec:
        selector:
          matchLabels:
            directory: rabbitmq
        accessModes:
          - ReadWriteOnce
        storageClassName: slow
        resources:
          requests:
            storage: 10Gi

- name: Add Bitnami Helm Repository
  kubernetes.core.helm_repository:
    state: present
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Install RabbitMQ Helm Chart
  kubernetes.core.helm:
    state: present
    wait: true
    update_repo_cache: true
    name: rabbitmq
    namespace: queue
    chart_ref: bitnami/rabbitmq
    values:
      namespaceOverride: queue
      auth:
        username: admin
        password: pass
      serviceAccount:
        create: false
      persistence:
        existingClaim: rabbitmq-nfs-pvc
      ingress:
        enabled: true
      metrics:
        enabled: true
        serviceMonitor:
          namespace: monitoring
          default:
            enabled: true
          perObject:
            enabled: true
          detailed:
            enabled: true
