---

- name: Get NFS Service
  register: service
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: nfs-server
    namespace: storage

- name: Save NFS Server IP
  ansible.builtin.set_fact:
    storage_ip: "{{ service.resources[0].spec.clusterIP}}"
