---

- name: Create Directory for Docker GPG Key
  become: true
  ansible.builtin.file:
    state: directory
    path: /etc/apt/keyrings
    mode: '0755'

- name: Add Docker GPG Key
  become: true
  ansible.builtin.apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Add Docker Apt Repository
  become: true
  ansible.builtin.apt_repository:
    state: present
    filename: docker
    repo: >-
      deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

- name: Install Docker and Dependencies
  ansible.builtin.include_role:
    name: apt_pkg
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Add Docker Group
  become: true
  ansible.builtin.group:
    state: present
    name: docker

- name: Add User to Docker Group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable and Start Docker services
  become: true
  loop:
    - docker.service
    - containerd.service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    service: "{{ item }}"
