global:
  scrape_interval: 15s
  external_labels:
    monitor: 'microk8s-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'microk8s'
    static_configs:
      - targets: ['10.0.1.1:9100']