---

- name: Create Persistence Directories
  hosts: server
  tasks:
    - name: Create Postgres Directory
      ansible.builtin.file:
        state: directory
        path: /mnt/data/postgres

    - name: Create Grafana Directory
      ansible.builtin.file:
        state: directory
        path: /mnt/data/grafana
        mode: '0777'

    - name: Create Prometheus Directory
      ansible.builtin.file:
        state: directory
        path: /mnt/data/prometheus
        mode: '0777'

    - name: Create Loki Directory
      ansible.builtin.file:
        state: directory
        path: /mnt/data/loki
        mode: '0777'
