$ANSIBLE_VAULT;1.1;AES256
66616533653331373832626330356638303066396666643963623330313434313533633939376166
6237646130633161366339346662333731303466653139370a313339616566663433306531383739
35613735393833343338303130336533373537363734323361396461623137343739386135393861
3363396262396233320a613231653337353232356633633435616462623531613239393836303265
34323436636634656438323034363064633665383265343930623236663862643166333938336631
35623063316438343866343437613533326432343662346638303464336363626331316231356638
646632623633326333313765356538643564
