---

- name: Get External HDD UUID
  register: lsblk
  ansible.builtin.shell: "lsblk -o UUID {{ drive }} | grep -v UUID"

- name: Update fstab
  become: true
  ansible.builtin.lineinfile:
    state: present
    path: /etc/fstab
    search_string: "{{ lsblk.stdout }}"
    line: UUID={{ lsblk.stdout }} /nfs ntfs defaults 0 0
